/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zach
 */
import java.util.ArrayList;
import java.util.HashMap;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import java.util.Vector;
import java.io.FileWriter;
import java.io.PrintWriter;

public class GUI extends javax.swing.JFrame {

    /**
     *  BEGIN AUTO GENERATED BY NetBeans
     */


    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        OutputOptionsTextBox = new javax.swing.JLabel();
        OutputOptionsTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        outputTable = new javax.swing.JTable();
        parameterComboBox2 = new javax.swing.JComboBox<>();
        parameterComboBox1 = new javax.swing.JComboBox<>();
        searchTxtField1 = new javax.swing.JTextField();
        searchTxtField2 = new javax.swing.JTextField();
        conjunctionComboBox1 = new javax.swing.JComboBox<>();
        searchTypeComboBox = new javax.swing.JComboBox<>();
        SearchTypeTextBox = new javax.swing.JLabel();
        OutputOptionsRadioButton1 = new javax.swing.JRadioButton();
        OutputOptionsRadioButton2 = new javax.swing.JRadioButton();
        SearchParametersTextBox = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        baconSearchTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        baconOutputTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        baconSearchTxtField1 = new javax.swing.JTextField();
        baconSearchButton = new javax.swing.JButton();
        excludeBaconTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yearStartYearTxtBox = new javax.swing.JTextField();
        yearEndYearTxtBox = new javax.swing.JTextField();
        yearResultBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        yearSearchButton = new javax.swing.JButton();
        excludeTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        genreSearchTxtField = new javax.swing.JTextField();
        genreSearchBox = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        genreOutputTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(400, 400));

        OutputOptionsTextBox.setText("Output Options:");

        OutputOptionsTextField.setText("File Name...");

        searchButton.setText("Search!");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        outputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(outputTable);

        parameterComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TITLE", "ACTOR", "PRODUCER", "DIRECTOR", "RUNTIME" }));

        parameterComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TITLE", "ACTOR", "PRODUCER", "DIRECTOR", "RUNTIME" }));
       

        searchTxtField1.setToolTipText("Enter Search Criteria...");

        searchTxtField2.setToolTipText("Optional Search Criteria...");

        conjunctionComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AND", "OR" }));

        searchTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MOVIE", "TVSERIES", "TVSPECIAL", "TVMOVIE", "TVMINISERIES", "TVSHORT", "SHORT", "VIDEO", "VIDEOGAME" }));

        SearchTypeTextBox.setText("Search type:");

        buttonGroup1.add(OutputOptionsRadioButton1);
        OutputOptionsRadioButton1.setSelected(true);
        OutputOptionsRadioButton1.setText("Text");

        buttonGroup1.add(OutputOptionsRadioButton2);
        OutputOptionsRadioButton2.setText("File:");

        SearchParametersTextBox.setText("Search Parameters:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addComponent(conjunctionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchTxtField2)
                            .addComponent(searchTxtField1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(parameterComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parameterComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(OutputOptionsTextBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(OutputOptionsRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(OutputOptionsRadioButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(OutputOptionsTextField))
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(149, 149, 149)
                                    .addComponent(searchButton))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(SearchTypeTextBox)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(SearchParametersTextBox))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTypeTextBox)
                    .addComponent(searchTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(SearchParametersTextBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(searchTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conjunctionComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(searchTxtField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(parameterComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(parameterComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OutputOptionsTextBox)
                    .addComponent(OutputOptionsRadioButton1)
                    .addComponent(OutputOptionsRadioButton2)
                    .addComponent(OutputOptionsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Search Queries", jPanel1);

        

        jLabel1.setText("This function find the degrees of seperation between an actor/actress and Kevin Bacon.");

        jLabel2.setText("Connect this actor/actress:");

        baconOutputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(baconOutputTable);

        jLabel3.setText("To this actor/actress:");

      

        baconSearchButton.setText("Search!");
        baconSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baconSearchButtonActionPerformed(evt);
            }
        });
        
       
        jLabel10.setText("Exclude From Chain:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(baconSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(baconSearchButton)
                                .addComponent(baconSearchTxtField1, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(excludeBaconTextField)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(baconSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(baconSearchTxtField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excludeBaconTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baconSearchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bacon Number", jPanel2);

        jLabel4.setText("Start Year:");

        jLabel5.setText("End Year:");

        yearStartYearTxtBox.setText("YYYY");
        

        yearEndYearTxtBox.setText("YYYY");
        

        yearResultBox.setEditable(false);
        

        jLabel6.setText("Result:");

        jLabel7.setText("This funtion identifies an actor/actress who has acted in");

        jLabel8.setText("a film every year in the specified date range. ");

        yearSearchButton.setText("Search!");
        yearSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearSearchButtonActionPerformed(evt);
            }
        });
        

        jLabel9.setText("Exclude: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearResultBox))
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(excludeTextField)
                            .addComponent(yearSearchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yearEndYearTxtBox)
                            .addComponent(yearStartYearTxtBox))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yearStartYearTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearEndYearTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excludeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yearSearchButton)
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearResultBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(336, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Year Range Search", jPanel3);

        jLabel11.setText("This funtion tallies the genres a particular director has worked with in film.");

        jLabel12.setText("Enter a director:");

        genreSearchBox.setText("Search!");
        genreSearchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreSearchBoxActionPerformed(evt);
            }
        });

        genreOutputTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(genreOutputTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(genreSearchBox)
                                .addComponent(genreSearchTxtField))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(genreSearchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(genreSearchBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Genre Search", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * END AUTO GENERATED BY NetBeans
     */
    
    
    private void yearSearchButtonActionPerformed(java.awt.event.ActionEvent evt){
        yearSearchButton.setEnabled(false);
        int startYear, endYear;
        
        //Ensure that integers are passed as parameters
        try{
            startYear = Integer.parseInt(yearStartYearTxtBox.getText());
            endYear = Integer.parseInt(yearEndYearTxtBox.getText());
        }catch(Exception e){
            e.printStackTrace();
            yearSearchButton.setEnabled(true);
            return;
        }
        String excludeActor = excludeTextField.getText().trim();
        
        SearchTerm term = new SearchTerm("", "", SearchTerm.TermType.YEAR, startYear, endYear);
        
        //Run the query on a separate thread in order to keep the UI responsive
        new Thread(new Runnable(){
            public void run(){
                String actor = dbAccessor.getActorFromYears(term, excludeActor);
                yearResultBox.setText(actor);
                yearSearchButton.setEnabled(true);
            }
        }).start();
    }


    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        //Disable search button so user can't send multiple queries
        searchButton.setEnabled(false);

        ArrayList<SearchTerm> terms = new ArrayList<SearchTerm>();
        String searchTerm1 = searchTxtField1.getText().trim();
        String searchTerm1Type = parameterComboBox1.getSelectedItem().toString();
        String conjunction = conjunctionComboBox1.getSelectedItem().toString();
        String searchTerm2 = searchTxtField2.getText().trim();
        String searchTerm2Type = parameterComboBox2.getSelectedItem().toString();

        //Cancel the request if there is nothing in the first text field
        if(searchTerm1.isEmpty()){
            searchButton.setEnabled(true);
            return;
        }

        terms.add(new SearchTerm(searchTerm1, "", SearchTerm.TermType.valueOf(searchTerm1Type), 0, 0));

        if(!searchTerm2.isEmpty()){
            terms.add(new SearchTerm(conjunction, "", SearchTerm.TermType.valueOf(conjunction), 0, 0));
            terms.add(new SearchTerm(searchTerm2, "", SearchTerm.TermType.valueOf(searchTerm2Type), 0, 0));
        }

        //Run the query on a separate thread in order to keep the UI responsive
        new Thread(new Runnable(){
            public void run(){
                ResultSet results = dbAccessor.requestMovies(terms, searchTypeComboBox.getSelectedItem().toString());
                if(OutputOptionsRadioButton1.isSelected()){
                    updateQueryTable(results);
                }else{
                    outputFile(results, OutputOptionsTextField.getText());
                }
                searchButton.setEnabled(true);
            }
        }).start();
    }


    private void baconSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        baconSearchButton.setEnabled(false);
        String actor1 = baconSearchTxtField.getText();
        String actor2 = baconSearchTxtField1.getText();
        String excludeActor = excludeBaconTextField.getText();
        
        if(actor1.equalsIgnoreCase(actor2) || actor1.equals("") || actor2.equals("") ||actor1.equalsIgnoreCase(excludeActor) || actor2.equalsIgnoreCase(excludeActor)){
            baconSearchButton.setEnabled(true);
            return;
        }
        
        SearchTerm term = new SearchTerm(actor1, actor2, SearchTerm.TermType.ACTOR, 0, 0);
        
        new Thread(new Runnable(){
            public void run(){
                ArrayList<String[]> path = dbAccessor.getLinkBetween(term, excludeActor);
                if(path.isEmpty()){
                    baconSearchButton.setEnabled(true);
                    return;
                }
                
                //Turn the path into a table
                DefaultTableModel model = new DefaultTableModel();
                model.addColumn("Actor1");
                model.addColumn("Actor2");
                model.addColumn("Movie");
                
                //Iterate through the path backwards since the path was constructed from goal->source instead of source->goal
                for(int i=path.size()-1; i>=0; i--){
                    Vector<String> row = new Vector<String>();
                    //Index 0 and 1 contain actor names, index 2 is the title that links them
                    row.addElement(path.get(i)[0]);
                    row.addElement(path.get(i)[1]);
                    row.addElement(path.get(i)[2]);
                    model.addRow(row);
                }
                
                SwingUtilities.invokeLater(new Runnable(){
                    public void run(){
                        baconOutputTable.setModel(model);
                        baconSearchButton.setEnabled(true);
                    }
                });
            }
        }).start();
        
    }

    private void genreSearchBoxActionPerformed(java.awt.event.ActionEvent evt) {
        genreSearchBox.setEnabled(false);
        String directorName = genreSearchTxtField.getText();
        new Thread(new Runnable(){
            public void run(){
                HashMap<String, Integer> result = dbAccessor.getDirectorsMovies(directorName);
                updateGenreCountTable(result);
                genreSearchBox.setEnabled(true);
            }
        }).start();
        
    }

    //Updates the table for standard queries
    private void updateQueryTable(ResultSet results){
        try{
            ResultSetMetaData metaData = results.getMetaData();
            DefaultTableModel model = new DefaultTableModel();

            //Add the columns to the new model
            for(int i=1; i<=metaData.getColumnCount(); i++){
                model.addColumn(metaData.getColumnLabel(i));
            }

            //Populate the model with the new rows
            while(results.next()){
                Vector<Object> row = new Vector<Object>();
                for(int i=1; i<=metaData.getColumnCount(); i++){
                    row.addElement(results.getObject(i));
                }
                model.addRow(row);
            }

            //Update the table with tne new model
            SwingUtilities.invokeLater(new Runnable(){
                public void run(){
                    outputTable.setModel(model);
                }
            });
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    //Updates the table for genre count
    public void updateGenreCountTable (HashMap<String, Integer> results){
        try{
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Genre");
            model.addColumn("Count");
            
            for(HashMap.Entry<String, Integer> entry: results.entrySet()){
                Vector<Object> row = new Vector<Object>();
                //Key is the genre name. Value is the count
                row.addElement(entry.getKey());
                row.addElement(entry.getValue());
                model.addRow(row);
            }
    
            // update the table with the populated model
            SwingUtilities.invokeLater(new Runnable(){
                public void run(){
                    genreOutputTable.setModel(model);
                }
            });
        }catch(Exception e){
            e.printStackTrace();
        }
    }


    /*
     * Output method inspired by
     * http://www.jicdesign.com/blog/java-writing-data-to-a-tab-delimited-file/
     */
    private void outputFile(ResultSet results, String filename){
        try{
            FileWriter output = new FileWriter(filename + ".tsv");
            PrintWriter printObj = new PrintWriter(output);
            ResultSetMetaData metaData = results.getMetaData();
            
            //Start by printing the column names
            for(int i=1; i<=metaData.getColumnCount(); i++){
                //Small check to ensure we don't use excess tabs
                if(i != 1){
                    printObj.print("\t");
                }
                printObj.print(metaData.getColumnLabel(i));
            }
            printObj.println();
            
            //Print the table data
            while(results.next()){
                for(int i=1; i<=metaData.getColumnCount(); i++){
                    //Small check to ensure we don't use excess tabs
                    if(i != 1){
                        printObj.print("\t");
                    }
                    printObj.print(results.getString(i));
                }
                printObj.println();
            }

            printObj.close();
            output.close();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
    /**
     * REMAINDER OF FILE AUTO GENERATED BY NetBeans
     */
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

	private DBAccessor dbAccessor = new DBAccessor();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OutputOptionsRadioButton1;
    private javax.swing.JRadioButton OutputOptionsRadioButton2;
    private javax.swing.JLabel OutputOptionsTextBox;
    private javax.swing.JTextField OutputOptionsTextField;
    private javax.swing.JLabel SearchParametersTextBox;
    private javax.swing.JLabel SearchTypeTextBox;
    private javax.swing.JTable baconOutputTable;
    private javax.swing.JButton baconSearchButton;
    private javax.swing.JTextField baconSearchTxtField;
    private javax.swing.JTextField baconSearchTxtField1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> conjunctionComboBox1;
    private javax.swing.JTextField excludeBaconTextField;
    private javax.swing.JTextField excludeTextField;
    private javax.swing.JTable genreOutputTable;
    private javax.swing.JButton genreSearchBox;
    private javax.swing.JTextField genreSearchTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable outputTable;
    private javax.swing.JComboBox<String> parameterComboBox1;
    private javax.swing.JComboBox<String> parameterComboBox2;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTxtField1;
    private javax.swing.JTextField searchTxtField2;
    private javax.swing.JComboBox<String> searchTypeComboBox;
    private javax.swing.JTextField yearEndYearTxtBox;
    private javax.swing.JTextField yearResultBox;
    private javax.swing.JButton yearSearchButton;
    private javax.swing.JTextField yearStartYearTxtBox;
    // End of variables declaration//GEN-END:variables
}